<a href="https://colab.research.google.com/github/pgordin/Grafy2022/blob/main/Cz%C4%99%C5%9B%C4%87_3_Funkcje_i_rekurencja.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Ciąg Fibonacciego

$$ 0, 1, 1, 2, 3, 5, 8, 13, 21, \dots $$
$$ a_n = \left \{ \begin{array}{lll}
n & \textrm{dla} & n \le 1 \\
a_{n-1}+a_{n-2} & \textrm{dla} & n > 1
\end{array}
\right. $$

In [ ]:
def fib1(n):
    if n <= 1:
        return n
    else:
        return fib1(n-1)+fib1(n-2)

print(fib1(30))

832040


In [ ]:
print(fib1(30)) # Fib1(40) raczejbym nie próbował.

832040


In [ ]:
def f():
  pass  # to jest pusty kod

print("Coś")

def ffib2(n):
  """
  n- ta liczba Fibonacciego przez programowanie dynamiczne
  """
  if n <= 1:
     return n
  else :  
    a, b = 0, 1
    for i in range(1, n):
      a, b = b, a + b
    return b

ffib2(400)

Coś


176023680645013966468226945392411250770384383304492191886725992896575345044216019675

In [ ]:
def fib2(n):
    if n <= 1:
        return n
    else:
        tabl = [0, 1]
        for i in range(2, n+1):
            tabl.append(tabl[i-1]+tabl[i-2])
        return tabl[n]
    
print(fib2(30))
print((1+(5)**(1/2))/2)
print((((1-(5)**(1/2))/2)))
print(((1+(5)**(1/2))/2)**(10)) # tyle razy dłużej liczy się o 10 większa liczba wg rekurencji

832040
1.618033988749895
-0.6180339887498949
122.99186938124426


In [ ]:
def fib3(n):
    return round((((1+(5)**(1/2)))**(n)-((1-(5)**(1/2)))**(n))/2**n/5**(1/2))

print(fib3(30))

832040


## Największy i najmniejszy element listy

In [ ]:
import random
def minimax1(a):
    return min(a), max(a)

a = [random.random() for _ in range(100000)]
print(minimax1(a))

(1.2188843976468355e-05, 0.9999976880740077)


Algorytmiczne podejście.

In [ ]:
def minimax2(a):
    min1, max1 = a[0], a[0]
    for x in a:
        if x < min1:
            min1 = x
        elif x > max1:
            max1 = x
    return min1, max1

print(minimax2(a))

(1.2188843976468355e-05, 0.9999976880740077)


Podzielmy listę na cześci - będzie mniej porównań.

In [ ]:
def minimax3(a):
    leng = len(a)
    if leng <= 2:
        return min(a), max(a)
    else:
        x = leng // 2
        min1, max1 = minimax3(a[0:x])
        min2, max2 = minimax3(a[x:leng])
        if min1 < min2:
            min3 = min1
        else: 
            min3 = min2
        if max1 > max2:
            max3 = max1
        else:
            max3 = max2
        return min3, max3

In [ ]:
def minimax4(a, d, g):
    leng = g - d
    if leng <= 2:
        min1 = max1 = a[d]
        if a[g-1] < min1:
            min1 = a[g-1]
        else: # if a[g-1] > max1:
            max1 = a[g-1]
        return min1, max1
    else:
        x = leng // 2
        min1, max1 = minimax4(a, d, d + x)
        min2, max2 = minimax4(a, d + x, g)
        if min1 < min2:
            min3 = min1
        else: 
            min3 = min2
        if max1 > max2:
            max3 = max1
        else:
            max3 = max2
        return min3, max3
    
print(minimax1(a))
print(minimax4(a, 0, len(a)))

(1.2188843976468355e-05, 0.9999976880740077)
(1.2188843976468355e-05, 0.9999976880740077)


Porównanie czasów wykonania

In [ ]:
%timeit -n100 mm1 = minimax1(a)
%timeit -n100 mm2 = minimax2(a)
%timeit -n100 mm3 = minimax3(a)
%timeit -n100 mm4 = minimax4(a, 0, len(a))

100 loops, best of 5: 3.86 ms per loop
100 loops, best of 5: 6.73 ms per loop
100 loops, best of 5: 80.4 ms per loop
100 loops, best of 5: 55.3 ms per loop


## Ciąg Fibonacciego raz jeszcze

Niech
$$ A = \left[ \begin{array}{cc}
1 & 1 \\
1 & 0
\end{array}
\right] = \left[ \begin{array}{cc}
a_2 & a_1 \\
a_1 & a_0
\end{array}
\right], \qquad B = \left[ \begin{array}{cc}
a_n & a_{n-1} \\
a_{n-1} & a_{n-2}
\end{array}
\right].$$

Wówczas
$$ A B = \left[ \begin{array}{cc}
a_{n+1} & a_{n} \\
a_{n} & a_{n-1}
\end{array}
\right].$$

Zatem
$$ A^{n} = \left[ \begin{array}{cc}
a_{n+1} & a_{n} \\
a_{n} & a_{n-1}
\end{array}
\right].$$

Sprawdźmy to!

In [ ]:
import numpy as np

A = np.array([[1,1],[1,0]])
print(A)
B = A.copy()
for i in range(1,10):
    B = np.matmul(A, B)
    print("-----------------")
    print(B)

[[1 1]
 [1 0]]
-----------------
[[2 1]
 [1 1]]
-----------------
[[3 2]
 [2 1]]
-----------------
[[5 3]
 [3 2]]
-----------------
[[8 5]
 [5 3]]
-----------------
[[13  8]
 [ 8  5]]
-----------------
[[21 13]
 [13  8]]
-----------------
[[34 21]
 [21 13]]
-----------------
[[55 34]
 [34 21]]
-----------------
[[89 55]
 [55 34]]


In [ ]:
def fib4(n):
    A = np.array([[1,1],[1,0]], dtype = np.longfloat)
    n = n - 1
    B = np.eye(2, dtype = np.longfloat)
    while n > 0:
        if n % 2 == 1:
            B = np.matmul(A, B)
        A = np.matmul(A, A)
        n = n // 2
    return B[0,0]
    
print((fib4(20)))
print(fib2(200)) # właściwe rozwiązanie - python ma nieskończoną dokładność/precyzję
print(round(fib4(200))) # przybliżone

6765.0
280571172992510140037611932413038677189525
280571172992510140032613988474878150311936


Macierze Fibonacciego bez numpy

In [ ]:
def mmul(A, B):
  """
  Mnożenie dwóch macierzy 2 x 2 (podanych jako lista 4 elementowa, wierszami)
  """
  return [A[0]*B[0]+ A[1]*B[2], A[0]*B[1] + A[1]*B[3], A[2]*B[0] + A[3]*B[2], A[2]*B[1]+A[3]*B[3]]

def fib5(n):
    A = [1,1,1,0]
    n = n - 1
    B = [1,0,0,1]
    while n > 0:
        if n % 2 == 1:
            B = mmul(A, B)
        A = mmul(A, A)
        n = n // 2
    return B[0]

print(fib5(20))
print(fib2(200)) 
print(fib5(200)) # to samo, bo pracujemy na int

6765
280571172992510140037611932413038677189525
280571172992510140037611932413038677189525


## Karty

In [ ]:
king = 'Krol'
queen = 'Dama'
jack = 'Walet'
ace = 'As'

hearts = 'kier'
diamonds = 'karo'
clubs = 'trefl'
spades = 'pik'

kolor = [hearts, diamonds, clubs, spades]
figura =[]
for i in range(2,11,1):
    figura.append(str(i))
figura.append(jack)
figura.append(queen)
figura.append(king)
figura.append(ace)

talia = []
for k in kolor:
    for f in figura:
        talia.append(f+" "+ k)
print(talia)

#alternatywnie
kolory = np.char.array(kolor)
figury = np.char.array(figura)
k, f = np.meshgrid(kolory, figury)
talia2 = f + ' ' + k

rng = np.random.default_rng()

def losowanie(talia, k):
    if k <= len(talia):
        return rng.choice(talia, k, False)
    else:
        return talia
    
print("-----------------------------")
karty = losowanie(talia, 20)
poker = np.array(karty).reshape(4, 5)
print(poker)

print("-----------------------------")
karty = losowanie(talia2.ravel(), 20)
poker = np.array(karty).reshape(4, 5)
print(poker)

['2 kier', '3 kier', '4 kier', '5 kier', '6 kier', '7 kier', '8 kier', '9 kier', '10 kier', 'Walet kier', 'Dama kier', 'Krol kier', 'As kier', '2 karo', '3 karo', '4 karo', '5 karo', '6 karo', '7 karo', '8 karo', '9 karo', '10 karo', 'Walet karo', 'Dama karo', 'Krol karo', 'As karo', '2 trefl', '3 trefl', '4 trefl', '5 trefl', '6 trefl', '7 trefl', '8 trefl', '9 trefl', '10 trefl', 'Walet trefl', 'Dama trefl', 'Krol trefl', 'As trefl', '2 pik', '3 pik', '4 pik', '5 pik', '6 pik', '7 pik', '8 pik', '9 pik', '10 pik', 'Walet pik', 'Dama pik', 'Krol pik', 'As pik']
-----------------------------
[['4 pik' 'Krol karo' '2 kier' 'Walet karo' '10 trefl']
 ['3 trefl' '3 karo' 'Dama trefl' '7 kier' '3 kier']
 ['4 kier' '2 pik' '4 karo' '6 pik' '2 karo']
 ['5 pik' '5 trefl' '10 kier' 'As trefl' '7 pik']]
-----------------------------
[['Krol karo' 'Dama kier' '10 kier' '9 pik' '7 karo']
 ['6 trefl' '5 kier' 'As karo' 'As kier' '8 pik']
 ['2 trefl' '5 karo' 'Krol trefl' '3 karo' '2 kier']
 ['As pi