<a href="https://colab.research.google.com/github/pgordin/Grafy2022/blob/main/Grafy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importowanie pakietów.

In [1]:
import numpy as np
from random import random, seed

# Funkcje grafowe

In [9]:
def print_matrix(vertices, matrix):
  """
  Wypisuje na ekranie graf zadany jako macierz sąsiedztwa.
  """
  n = len(matrix)
  if (vertices is not None) and(len(vertices) ==n):
    vv = vertices
  else:
    vv = range(1, n+1)
  for i in range(n):
    print(vv[i], ":", end="")
    for j in range(n):
      if matrix[i,j]:
        print(" ", vv[j], end="")
    print("")

def print_graph(graph):
  """
  Wypisuje graf zadany jako słownik pythona.
  """
  for v in graph:
    print(v, ":", end="")
    for u in graph[v]:
      print(" ", u, end="")
    print("")

## Tworzenie grafu (jako listy sąsiedztwa)

In [16]:
def add_vertex(graph, vertex):
  """ Nowy wierzchołek do istniejącego grafu. """
  if vertex not in graph:
    graph[vertex] = []

def add_arc(graph, arc):
  """
  Dodaje nowy łuk (parę wierzchołków) do istniejącego grafu.
  Rozważamy grafy proste, skierowane
  """
  u, v = arc
  add_vertex(graph, u)
  add_vertex(graph, v)
  if v not in graph[u]:
    graph[u].append(v)

def add_edge(graph, edge):
  """
  Dodaje nową krawędź (parę wierzchołków) do istniejącego grafu,
  traktując graf nieskierowany jako prosty graf skierowny, ale symetryczny i bez pętli.
  """
  u, v = edge
  add_vertex(graph, u)
  add_vertex(graph, v)
  if u == v:
    raise ValueError("Pętla!")
  if v not in graph[u]:
    graph[u].append(v)
  if u not in graph[v]:
    graph[v].append(u)


# Przykłady wykorzystania

## Pierwszy, przykładowy graf


### Macierz sąsiedztwa

In [4]:
vertices = ["a", "b", "c", "d", "e", "f"]
matrix = np.array([[0,1,1,0,0,0],
                   [1,0,1,0,0,0],
                   [1,1,0,1,1,0],
                   [0,0,1,0,1,0],
                   [0,0,1,1,0,0],
                   [0,0,0,0,0,0]])
print(vertices)
print(matrix)
print("--------------------------")
print_matrix(vertices, matrix)
print("--------------------------")
print_matrix(None, matrix)

['a', 'b', 'c', 'd', 'e', 'f']
[[0 1 1 0 0 0]
 [1 0 1 0 0 0]
 [1 1 0 1 1 0]
 [0 0 1 0 1 0]
 [0 0 1 1 0 0]
 [0 0 0 0 0 0]]
--------------------------
a :  b  c
b :  a  c
c :  a  b  d  e
d :  c  e
e :  c  d
f :
--------------------------
1 :  2  3
2 :  1  3
3 :  1  2  4  5
4 :  3  5
5 :  3  4
6 :


### Lista sąsiedztwa

In [10]:
graph = {
    'a' : ['b',  'c'],
    'b' : ['a',  'c'],
    'c' : ['a', 'b', 'd', 'e'],
    'd' : ['c', 'e'],
    'e' : ['c', 'd'],
    'f' : []
}
print(graph)
print("--------------------------")
print_graph(graph)

{'a': ['b', 'c'], 'b': ['a', 'c'], 'c': ['a', 'b', 'd', 'e'], 'd': ['c', 'e'], 'e': ['c', 'd'], 'f': []}
--------------------------
a :  b  c
b :  a  c
c :  a  b  d  e
d :  c  e
e :  c  d
f :


### Modyfikacje grafu

In [20]:
add_vertex(graph, 'g')
add_arc(graph, ['a', 'g'])
add_arc(graph, ['g', 'a'])
add_edge(graph, ['a', 'h'])
add_edge(graph, ['d', 'h'])
#błąd add_edge(graph, ['h', 'h'])
add_arc(graph, ['h', 'h'])
print_graph(graph)

a :  b  c  g  h
b :  a  c
c :  a  b  d  e
d :  c  e  h
e :  c  d
f :
g :  a
h :  a  d  h


### Tworzenie grafów losowych $G(n, p)$.

In [21]:
# dla powtarzalności wyników
seed(2022)

In [23]:
# losuje grapf G(10, 1/3)
n = 10
p = 1/3
random_graph={}
for i in range(1, n+1):
  add_vertex(random_graph, i)
  for j in range(1, i):
    if random() < p:
      add_edge(random_graph, [i,j])

print_graph(random_graph)

1 :  4  7  9
2 :  3  6  8  9
3 :  2  7  9  10
4 :  1
5 :  8
6 :  2  8  9  10
7 :  1  3  9
8 :  2  5  6
9 :  1  2  3  6  7
10 :  3  6
